create table tbl_conference (
    id_conference integer generated by default as identity,
    address varchar(255) not null,
    name varchar(100) not null,
    primary key (id_conference)
);
 
create table tbl_session (
    session_id integer generated by default as identity,
    start_date date not null,
    start_time time(6) not null,
    title varchar(255) not null,
    primary key (session_id)
);

create table tbl_subscription (
    created_at timestamp(6) not null,
    level integer,
    unique_id varchar(45) not null,
    session_id integer not null,
    subscribed_user_id integer not null,
    primary key (session_id, subscribed_user_id)
);

create table tbl_user (
    user_id integer generated by default as identity,
    email varchar(255) not null,
    name varchar(255) not null,
    primary key (user_id)
);

alter table if exists tbl_subscription
   add constraint fk_session_id
   foreign key (session_id)
   references tbl_session;

alter table if exists tbl_subscription
   add constraint fk_subscribed_user_id
   foreign key (subscribed_user_id)
   references tbl_user;