spring:
  application:
    name: event
  datasource:
    url: jdbc:postgresql://${host}:${port}/${database}
    username: ${dbuser}
    password: ${dbpass}
    hikari:
      connection-timeout: ${connection_timeout:30000}
      idle-timeout: ${idle_timeout:600000}
      max-lifetime: ${max_lifetime:1800000}
      maximum-pool-size: ${maximum_pool_size:10}
      minimum-idle: ${minimum_idle:5}
      pool-name: ${pool_name:eventApiPool}
      auto-commit: true
      validation-timeout: ${validation_timeout:5000}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    validate-on-migrate: true