spring:
  application:
    name: event
  datasource:
    url: jdbc:postgresql://172.240.0.2:5432/eventsdb
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    repair-on-migrate: false
    clean-on-validation-error: false
    validate-on-migrate: true